"""Add password_hash field to Owner model for login functionality

Revision ID: 8198cd94002e
Revises: f673ae2e96ed
Create Date: 2025-02-17 04:37:41.123564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8198cd94002e'
down_revision = 'f673ae2e96ed'
branch_labels = None
depends_on = None


def upgrade():
    # Use batch_alter_table to support SQLite:
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
