""" Add image_url field to Pet

Revision ID: f673ae2e96ed
Revises: ba748b90b57c
Create Date: 2025-02-17 04:20:20.295561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f673ae2e96ed'
down_revision = 'ba748b90b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
